<?php

namespace AppBundle\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * SubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends NestedTreeRepository
{
    public function getRoot()
    {
        // TODO clean roots
        $roots = $this->getRootNodes();
        return $roots[0];
    }

    public function getRootSubjects()
    {
        // TODO clean roots
        $roots = $this->getRootNodes();
        $root = $roots[0];

        return $root->getChildren();
    }
}